### ISSUE TITLE
jax-rs-pac4j + Custom ExceptionMapper

### ISSUE THREAD

**Issue by sebargarcia** [pac4j/jax-rs-pac4j#13]
When a 401 Unathorized is thrown by pac4j SecurityFilter no exception is call, so we can not use Exception mapper.
Use case reported here:
https://groups.google.com/forum/#!topic/pac4j-users/EaCtHEgiWm4

**Comment by victornoel** [comment]
Thanks @sebargarcia, I'm going to take a look at that :)

**Comment by victornoel** [comment]
Ok, first thing, `Exception` thrown in `ContainerRequestFilter` are passed to an `ExceptionMapper` if there is one (both in jersey and resteasy), that's a good news :)
Now I have to think about which exception to use to represent pac4j http response, and maybe introduce a default `ExceptionMapper` for those... still more to investigate!

**Comment by victornoel** [comment]
After some thought, I'm not so sure anymore this is a matter of changing something in jax-rs-pac4j...

Maybe it would simply be better for you to extend the JAX-RS filter (`CallbackFilter` I guess) and override `org.pac4j.jax.rs.filters.AbstractFilter.adapter()` to define how to build the `Response` depending on the outcome of pac4j logic...

I'm not totally comfortable with how things are organised in pac4j regarding this... @leleuj could you help me here? Basically, @sebargarcia wants to define its own response in case of various errors (mostly 401 if I understood well, maybe also 403, if there is some in pac4j) instead of letting pac4j do it itself.
In jax-rs-pac4j, the error built via the `WebContext` is directly transformed into an HTTP response.
By the way @leleuj, I would be curious as to why the `HttpActionAdapter` does not take a whole `HttpAction` instead of just its http code?

Also, @sebargarcia, note something important: I feel like you started with an `ExceptionMapper` because you were interested in the `TechnicalException` thrown by jwt for the case `Cannot decrypt / verify JWT`. This situation is no longer true with pac4j 2.0.0 (even though for now it is...) since this mistake was fixed: it should be a `CredentialException` and thus it should not find itself caught by an `ExceptionMapper` because it should never result into an Exception thrown by the filter (all the exception thrown by pac4j's filters are `RuntimeException` and most of the time `TechnicalException` that are not meant to be seen by the client, they should result in 500 error). In particular we don't throw the JAX-RS `Exception` such as `NotAuthorizedException` (but I guess if an Authenticator needed to parse the body of a request and couldn't, it could throw a `BadRequestException`...).

I think the best for pac4j's jax-rs filters would be to:
 - throw all the exceptions already automatically taken into account by jersey or whatever jax-rs implementation is used
 - build a response for the cases pertaining to security  (and not to throw an `Exception` as I started to say in my first answer to this issue) such as 401, 403, redirect to identity provider, etc.

So for a user of jax-rs-pac4j, customisation of this later aspect should be through overriding of the `HttpActionAdapter`... maybe it means we could ease its overriding, maybe via a setter, and also maybe in dropwizard-pac4j...

Comments @leleuj? @evnm maybe too? :)

**Comment by sebargarcia** [comment]
Hi Victor, thanks for the time invested in this topic. First of all sorry for my english. 
Indeed what I really want is send in JSON format a message about the error and the correct http status code (I mean define my own response in case of errors).  I don't want to send the default error page, instead I want to send a JSON message (and in spanish language).
I understood what you say, but why pac4j not throw an Exception when it is unathorized? 
I think it sould thrown an Exception so we can catch it.
Thanks for all.

**Comment by sebargarcia** [comment]
This helps me. https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-2rd-edition/content/en/part1/chapter7/exception_handling.html

**Comment by victornoel** [comment]
I see what you mean, but if we start throwing exceptions in specific cases and not throwing exceptions in others (e.g. 403 or 302), it's going to be difficult to have a clear idea of pac4j's behaviour.

And by the way, the `NotAuthorizedException` is meant to be used at the client side, not at the server side. If you look at Jersey's code, they are not taken into account by Jersey server, they are only used to transform from a `Response` to an `Exception` when there is a client call failing.

So, what you need is either to plug into pac4j (via class extension as explained before) or add a `ContainerResponseFilter` and use it to build the desired response in the desired cases.
Though, for the specific case of the `TechnicalException` for JWT, you still need an `ExceptionMapper` until pac4j 2.0 is released :)

**Comment by leleuj** [comment]
Jumping into this discussion.

Once again, we must never forget that pac4j is a security engine at first, meant to be used in many frameworks, from J2E to JAX-RS and this implies some behaviours / constraints.

The security filter/controller delegates to the security logic which performs its logic on the specific web context of the framework (`JaxRsContext` here). If it's not enough, the `HttpActionAdapter` handles the extra logic (it must be settable at the filter/controller level).
In J2E, the mapping is done in the web.xml file. In Spring Web MVC, a specific controller handles the error use cases: https://github.com/pac4j/spring-webmvc-pac4j-boot-demo/blob/master/src/main/java/org/pac4j/demo/spring/MyErrorController.java
In Play, we use a specific `HttpActionAdapter`: https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/controllers/DemoHttpActionAdapter.java

So far, providing the HTTP status code to the `HttpActionAdapter` has been sufficient.

If  the `ExceptionMapper` is a standard mechanism in JAX-RS, the default `HttpActionAdapter` should throw exceptions for it. Otherwise, you should define a custom `HttpActionAdapter`.

**Comment by victornoel** [comment]
I think that ExceptionMapper is a standard mechanism to handle resource or extra libraries' exception.
In that way, it could be used by pac4j, but it would mean for us to:
 - define new exceptions for each of the possible outcomes of pac4j's behaviour
 - define a default ExceptionMapper

I think it is a lot of  work for a cumbersome use (because it means that the user has to handle this extra knowledge) instead of simply having the normal way of aborting a request via JAX-RS `context.abort()` (the currently provided implementation of `HttpActionAdapter`).

**Comment by victornoel** [comment]
For the record, in JAX-RS, the `ErrorController` would be implemented using a `ContainerResponseFilter` I think.

**Comment by sebargarcia** [comment]
Now I see! thank you guys for the information. I will do some tests and then tell you!

**Comment by victornoel** [comment]
@sebargarcia are you using dropwizard-pac4j or simply jax-rs-pac4j? Don't hesitate to ask for more details on how to solve this problem in particular on the mailing list :)
I will keep this issue open until #15 is solved, because it would be the clean way of fixing your problem I think.

**Comment by sebargarcia** [comment]
Great! Thanks! I am using jax-rs-pac4j on Payara Server.

**Comment by victornoel** [comment]
Closing this, let's continue discussion on the user mailing list :)
