### ISSUE TITLE
wrong version number

### ISSUE THREAD

**Issue by eroux** [pac4j/jax-rs-pac4j#20]
I think `2.0.1-SNAPSHOT` should be `2.1.0-SNAPSHOT` in order to follow pac4j versionning

**Comment by victornoel** [comment]
@eroux why? what changed since 2.0.0 that is a new feature? There was no commit...

**Comment by eroux** [comment]
It's just that looking at the [commit history](https://github.com/pac4j/jax-rs-pac4j/commits/master) it seems jax-rs-pac4j follows pac4j's version number, and is released at the same time. That may not be true, but I would be really puzzled if the version synchronization was purely fortuitous... and as pac4j's next version is 2.1.0, maybe jax-rs-pac4j could follow that and release a 2.1.0 version at the same time? If you decided to desynchronize the version numbering (why not after all), I think it should be made a little bit more clear, so that users don't use `<version>${pac4j.version}</version>` in their pom.xml file... but that's fine, you can close the issue if it's on purpose, it's just a bit confusing, not a real bug.

**Comment by millross** [comment]
There's no good reason why implementations should follow the pac4j core numbering. Quite the opposite in fact, an implementation's API could break independently of the pac4j API (requiring major version change) and if an implementation doesn't have new features, even if pac4j core does, then the implementation version will lag pac4j. For example vertx-pac4j had to go to version 3 because its API changed, even though pac4j was only going to version 2. It's unrealistic to expect the versions to match, especially as the framework/toolset may force an API change or new feature on the implementation entirely independently of pac4j.

**Comment by millross** [comment]
It would of course be nice if we could, but each implementation is working off 2 versionable elements - pac4j and the framework/toolset it applies to. You could equally argue that in fact jax-rs-pac4j should follow jax-rs versioning for clarity.

**Comment by victornoel** [comment]
thanks @millross for the explanation.
I understand your point of view @eroux, it makes sense, especially now because pac4j and jax-rs-pac4j versions match, but it won't always be the case.
It is true that there will be time when a new version of jax-rs-pac4j will be released at the same time as a pac4j version (and it will maybe happen for 2.1.0) but anyway, for now jax-rs-pac4j depends on pac4j 2.0.0 so it is good as it is, I will increment the version as needed depending on the commits we make :)

**Comment by eroux** [comment]
ok, thanks a lot for the explanation, that makes sense!
