### ISSUE TITLE
usage (and doc improvement)

### ISSUE THREAD

**Issue by eroux** [pac4j/jax-rs-pac4j#21]
Following the README is pretty clear until [section2](https://github.com/pac4j/jax-rs-pac4j#2-define-the-configuration-config--client--authorizer) which states

> The configuration (org.pac4j.core.config.Config) contains all the clients and authorizers required by the application to handle security.

and then cites a lot of code with no context (no function name, class, file name, etc.). I don't understand what to do with this code or what the sentence quoted above means. Can you please explain?

**Comment by victornoel** [comment]
@eroux in order to configure pac4j, you need to provide a `Config` object (like [this](https://github.com/pac4j/jax-rs-pac4j#jax-rs-configuration)).

The code simply shows examples of `Config` object, this is specific to pac4j, not jax-rs-pac4j, so you can do it wherever you want as long as you pass the config object to the various `Features` and `Providers` that you register into the JAX-RS resource.

Is this clearer?

**Comment by victornoel** [comment]
It is true that the documentation assumes that the reader is familiar with JAX-RS and pac4j, if you have ideas of improvements, I'm interested, but I don't have the time to write much more documentation right now :)

**Comment by eroux** [comment]
Thank you! Not really clerarer I'm affraid... I think the doc about the Config object is http://www.pac4j.org/docs/config.html but even with that I'm really puzzled on where it is used...? I'm familiar with JAX-RS but not with pac4j. In fact I'm trying to have a very little demo working and it's really complex... is there an software somewhere that uses pac4j and that I could get inspiration from?

**Comment by victornoel** [comment]
do you plan to use it exclusively with JAX-RS?

**Comment by victornoel** [comment]
(i.e. not with dropwizard)

**Comment by eroux** [comment]
yes, only JAX-RS, but I guess I can inspire from the code of the dropwizard app?

**Comment by victornoel** [comment]
ould you show me how you setup your jax-rs resources and features? Which container are you using (jersey, resteasy, grizzly, jetty, etc)? 
If you give me that, I will include pac4j in it and we can add it to the documentation as a self-contained example :)

**Comment by eroux** [comment]
That's very kind, thanks a lot! I only have a boilerplate now: https://github.com/BuddhistDigitalResourceCenter/auth-api I'm trying to figure out what to do to have, say `/login` to take a login/pass and spit a jwt token... (see the design doc of the repo) but I should probably start with more simple things!

**Comment by victornoel** [comment]
ok, I will get back to you soon :)

**Comment by victornoel** [comment]
For the record, I answered on the mailing list: https://groups.google.com/d/msg/pac4j-users/qjorvxOmSrk/mP4E6dgTCwAJ

**Comment by victornoel** [comment]
So, if you are interested to document this use case, you submit a PR :)

But before let's see ho it unravel, I opened two related issues in pac4j so maybe some better solutions will be found via discussion: pac4j/pac4j#938 and pac4j/pac4j#939

**Comment by bbarroux** [comment]
One of the most glaring issue is that the code fragments provided in the documentation are not correct/compilable anymore. 
The code fragment are based on an old version where the config was passed to JaxRsContextFactoryProvider, Pac4JSecurityFeature, etc as a constructor argument. 
This has been changed and is not an option anymore. 

So the reader is left trying different things and hope (without success in my case), that the jax-rs magical features/providers/context auto-weaving will finally pick up the config in a correct way.

**Comment by victornoel** [comment]
@bbarroux good point, any way for you to provide a PR to clarify or even simplify (if tests already exists that illustrate some points) the README?
Or at least a clear list of what is working and what is not?
Thanks :)

**Comment by victornoel** [comment]
I'm closing this, feel free to open a PR directly

**Comment by jwindhager** [comment]
I don't understand why this issue was closed. Many parts of the readme are still not correct/compilable, e.g. most code in the [JAX-RS configuration section](https://github.com/pac4j/jax-rs-pac4j#jax-rs-configuration). Also, [the dependencies section](https://github.com/pac4j/jax-rs-pac4j#1-add-the-required-dependencies-jax-rs-pac4j--pac4j--libraries) seems to be outdated (the latest version for [org.pac4j/jax-rs-pac4j](https://mvnrepository.com/artifact/org.pac4j/jax-rs-pac4j) is 2.3.0, I guess this should point to [org.pac4j.jax-rs/core](https://mvnrepository.com/artifact/org.pac4j.jax-rs/core) instead).

Personally, such documentation issues certainly don't increase my trust in this library and, after a day of struggling to get this working for my project, I won't try any further until they are resolved.

**Comment by leleuj** [comment]
Having a good/accurate documentation is a permanent issue. No need to create one for that.

This is an Open Source project, not a paid software. If the documentation is not accurate, it's ALSO up to you to help fixing the documentation.
