### ISSUE TITLE
inconsistent documentation (missing class)

### ISSUE THREAD

**Issue by mtmmtm9** [pac4j/jax-rs-pac4j#26]
The class JaxRsCallbackUrlResolver is not found. It was mentioned in the documentation.
How can I get this working ? Some demo-code would also be nice.

**Comment by leleuj** [comment]
Since pac4j v2, the `CallbackUrlResolver` has been renamed as `UrlResolver` as it's not only used for callbacks.
So the `JaxRsCallbackUrlResolver` is now named `JaxRsUrlResolver`: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsUrlResolver.java

I updated the README.
